+ Fix parse error.
Fixing issue #1 involved downloading cordova plugins.  Initially
this generated the following error:

There was an error opening your package.json file.
 SyntaxError: /path/to/package.json: Unexpected token ]
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:430:27)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.readInPackageJson (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:14:10)
    at Object.getPackageJson (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:23:25)
    at Object.restoreState (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:426:27)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/ionic/state.js:85:13)

The solution was to delete cordovaPlugins, and to allow

  ionic plugin add <plugin> ...

to recreate config.json.